# Site Info
title: Tech blog
tagline: '기술 블로그'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: https://joohyung1213.github.io
logo: '/public/lemon.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Joohyung Jeon
  description: 
  gravatar: #3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/joohyung-jeon-aa5615188
    github:    https://github.com/joohyung1213
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     #http://weibo.com/41173780
    email:     mailto:joohyung1213@gmail.com


# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://joohyung1213.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/9.jpg
  caption: Blade Runner 2049, 2017, Denis Villeneuve.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: #'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

